namespace Nox.Dashboard.Services;

public class LanguageService
{
    public string Lang { get; private set; } = "it";
    public event Action? OnChange;

    public string this[string key] =>
        _strings.TryGetValue(Lang, out var d) && d.TryGetValue(key, out var v) ? v : key;

    public void Toggle() => Set(Lang == "it" ? "en" : "it");

    public void Set(string lang)
    {
        if (Lang == lang) return;
        Lang = lang;
        OnChange?.Invoke();
    }

    private static readonly Dictionary<string, Dictionary<string, string>> _strings = new()
    {
        ["it"] = new()
        {
            // nav
            ["nav.orchestration"] = "Orchestrazione",
            ["nav.hitl_section"]  = "Human-in-the-Loop",
            ["nav.infra"]         = "Infrastruttura",
            ["nav.dashboard"]     = "Dashboard",
            ["nav.flows"]         = "Flow Designer",
            ["nav.agents"]        = "Agent Monitor",
            ["nav.review"]        = "Coda Revisione",
            ["nav.skills"]        = "Skill Approval",
            ["nav.mcp"]           = "MCP Servers",
            ["nav.footer"]        = "Piattaforma Nox",
            // common
            ["refresh"]    = "↺ Aggiorna",
            ["cancel"]     = "Annulla",
            ["approve"]    = "✓ Approva",
            ["reject"]     = "✗ Rifiuta",
            ["view_all"]   = "Vedi tutti →",
            ["no_data"]    = "Nessun dato disponibile.",
            ["status"]     = "Stato",
            ["name"]       = "Nome",
            ["type"]       = "Tipo",
            ["created"]    = "Creato",
            ["edit"]       = "✎ Modifica",
            ["delete"]     = "✕ Elimina",
            ["save"]       = "Salva",
            // home
            ["home.title"]         = "Orchestrazione Nox",
            ["home.subtitle"]      = "Simulazione software house multi-agente",
            ["home.pending"]       = "In Revisione",
            ["home.active_flows"]  = "Flow Attivi",
            ["home.running_agents"]= "Agent Attivi",
            ["home.skills_wait"]   = "Skill in Attesa",
            ["home.recent_runs"]   = "Run Recenti",
            ["home.run"]           = "Run",
            ["home.flow"]          = "Flow",
            ["home.started"]       = "Avviato",
            ["home.pending_card"]  = "Revisioni Pendenti",
            ["home.all_clear"]     = "Tutto a posto ✓",
            ["home.no_runs"]       = "Nessun run ancora.",
            ["home.flows_def"]     = "Flow definiti",
            ["home.templates"]     = "Template agente",
            ["home.active_skills"] = "Skill attive",
            ["home.mcp_servers"]   = "Server MCP",
            ["home.last_refresh"]  = "Ultimo aggiornamento",
            // flows
            ["flows.title"]       = "Flow Designer",
            ["flows.new"]         = "+ Nuovo Flow",
            ["flows.no_flows"]    = "Nessun flow. Crea il tuo primo flow per iniziare.",
            ["flows.nodes"]       = "nodi",
            ["flows.edges"]       = "archi",
            ["flows.view"]        = "Visualizza",
            ["flows.run"]         = "▶ Avvia",
            ["flows.recent"]      = "Run Recenti",
            ["flows.run_id"]      = "Run ID",
            ["flows.started"]     = "Avviato",
            ["flows.completed"]   = "Completato",
            ["flows.new_title"]   = "Nuovo Flow",
            ["flows.desc"]        = "Descrizione",
            ["flows.create"]      = "Crea",
            ["flows.node"]           = "Nodo",
            ["flows.outgoing"]       = "Archi Uscenti",
            ["flows.template_agent"] = "Template Agente (opzionale)",
            ["flows.no_template"]    = "Nessun template — solo Start/End",
            ["flows.template_hint"]  = "Selezionando un template verrà aggiunto un nodo AgentTask tra Start ed End.",
            // agents
            ["agents.title"]    = "Agent Monitor",
            ["agents.filter"]   = "Filtra per Flow Run ID",
            ["agents.no_data"]  = "Nessun agente trovato. Avvia un flow per vedere gli agenti.",
            ["agents.model"]    = "Modello",
            ["agents.tokens"]   = "Token",
            ["agents.subagents"]= "Sub-agent",
            ["agents.flow"]     = "Flow",
            ["agents.parent"]   = "Parent",
            ["agents.created"]  = "Creato",
            // hitl
            ["hitl.title"]      = "Coda Revisione HITL",
            ["hitl.live"]       = "Live",
            ["hitl.connecting"] = "Connessione...",
            ["hitl.no_pending"] = "Nessun checkpoint pendente. Gli agenti stanno lavorando...",
            ["hitl.expires"]    = "Scade",
            ["hitl.escalate"]   = "↑ Escalate",
            ["hitl.recent"]     = "Decisioni Recenti",
            ["hitl.title_col"]  = "Titolo",
            ["hitl.decision"]   = "Decisione",
            ["hitl.by"]         = "Da",
            ["hitl.at"]         = "Quando",
            // skills
            ["skills.title"]    = "Skill Registry & Approvazione",
            ["skills.pending"]  = "In attesa di approvazione",
            ["skills.no_pend"]  = "Nessuna skill in attesa di approvazione.",
            ["skills.def"]      = "Definizione",
            ["skills.active"]   = "Skill Attive",
            ["skills.filter"]   = "Filtra per slug o nome...",
            ["skills.slug"]     = "Slug",
            ["skills.scope"]    = "Scope",
            // mcp
            ["mcp.title"]       = "MCP Servers",
            ["mcp.no_data"]     = "Nessun server MCP trovato.",
            ["mcp.all"]         = "Tutti",
            ["mcp.endpoint"]    = "Endpoint",
            ["mcp.image"]       = "Immagine",
            ["mcp.proposed"]    = "Proposto da agente",
            ["mcp.approved_by"] = "Approvato da",
            ["mcp.tools"]       = "Tool",
            ["mcp.discover"]    = "🔍 Scopri Tool",
            // skills - create
            ["skills.new"]        = "+ Nuova Skill",
            ["skills.new_title"]  = "Nuova Skill",
            ["skills.mandatory"]  = "Obbligatoria (assegnata automaticamente)",
            ["skills.group"]      = "Gruppo (opzionale)",
            // agents - templates
            ["agents.tab_agents"]   = "Agenti",
            ["agents.tab_tpl"]      = "Template",
            ["agents.new_tpl"]      = "+ Nuovo Template",
            ["agents.new_tpl_title"]= "Nuovo Template Agente",
            ["agents.role"]         = "Ruolo",
            ["agents.max_sub"]      = "Max Sub-agent",
            ["agents.skill_groups"] = "Gruppi Skill (virgola separati)",
            ["agents.system_prompt"]= "System Prompt",
            ["agents.no_tpl"]       = "Nessun template. Creane uno.",
            ["agents.is_global"]    = "Template globale",
            ["agents.model"]        = "Modello",
            // nav - extras
            ["nav.wiki"]        = "Wiki",
            ["nav.docs"]        = "Documentazione",
            ["nav.monitor"]     = "Monitor Live",
            // monitoring sidebar
            ["mon.flows"]       = "flow attivi",
            ["mon.agents"]      = "agenti attivi",
            ["mon.hitl"]        = "revisioni HITL",
            ["mon.skills"]      = "skill in attesa",
        },
        ["en"] = new()
        {
            // nav
            ["nav.orchestration"] = "Orchestration",
            ["nav.hitl_section"]  = "Human-in-the-Loop",
            ["nav.infra"]         = "Infrastructure",
            ["nav.dashboard"]     = "Dashboard",
            ["nav.flows"]         = "Flow Designer",
            ["nav.agents"]        = "Agent Monitor",
            ["nav.review"]        = "Review Queue",
            ["nav.skills"]        = "Skill Approval",
            ["nav.mcp"]           = "MCP Servers",
            ["nav.footer"]        = "Nox Platform",
            // common
            ["refresh"]    = "↺ Refresh",
            ["cancel"]     = "Cancel",
            ["approve"]    = "✓ Approve",
            ["reject"]     = "✗ Reject",
            ["view_all"]   = "View all →",
            ["no_data"]    = "No data available.",
            ["status"]     = "Status",
            ["name"]       = "Name",
            ["type"]       = "Type",
            ["created"]    = "Created",
            ["edit"]       = "✎ Edit",
            ["delete"]     = "✕ Delete",
            ["save"]       = "Save",
            // home
            ["home.title"]         = "Nox Orchestration",
            ["home.subtitle"]      = "Multi-agent software house simulation",
            ["home.pending"]       = "Pending Reviews",
            ["home.active_flows"]  = "Active Flows",
            ["home.running_agents"]= "Running Agents",
            ["home.skills_wait"]   = "Skills Pending",
            ["home.recent_runs"]   = "Recent Flow Runs",
            ["home.run"]           = "Run",
            ["home.flow"]          = "Flow",
            ["home.started"]       = "Started",
            ["home.pending_card"]  = "Pending Reviews",
            ["home.all_clear"]     = "All clear ✓",
            ["home.no_runs"]       = "No runs yet.",
            ["home.flows_def"]     = "Flows defined",
            ["home.templates"]     = "Agent templates",
            ["home.active_skills"] = "Active skills",
            ["home.mcp_servers"]   = "MCP servers",
            ["home.last_refresh"]  = "Last refresh",
            // flows
            ["flows.title"]       = "Flow Designer",
            ["flows.new"]         = "+ New Flow",
            ["flows.no_flows"]    = "No flows yet. Create your first flow to get started.",
            ["flows.nodes"]       = "nodes",
            ["flows.edges"]       = "edges",
            ["flows.view"]        = "View",
            ["flows.run"]         = "▶ Run",
            ["flows.recent"]      = "Recent Runs",
            ["flows.run_id"]      = "Run ID",
            ["flows.started"]     = "Started",
            ["flows.completed"]   = "Completed",
            ["flows.new_title"]   = "New Flow",
            ["flows.desc"]        = "Description",
            ["flows.create"]      = "Create",
            ["flows.node"]           = "Node",
            ["flows.outgoing"]       = "Outgoing Edges",
            ["flows.template_agent"] = "Agent Template (optional)",
            ["flows.no_template"]    = "No template — Start/End only",
            ["flows.template_hint"]  = "Selecting a template adds an AgentTask node between Start and End.",
            // agents
            ["agents.title"]    = "Agent Monitor",
            ["agents.filter"]   = "Filter by Flow Run ID",
            ["agents.no_data"]  = "No agents found. Start a flow run to see agents here.",
            ["agents.model"]    = "Model",
            ["agents.tokens"]   = "Tokens",
            ["agents.subagents"]= "Sub-agents",
            ["agents.flow"]     = "Flow",
            ["agents.parent"]   = "Parent",
            ["agents.created"]  = "Created",
            // hitl
            ["hitl.title"]      = "HITL Review Queue",
            ["hitl.live"]       = "Live",
            ["hitl.connecting"] = "Connecting...",
            ["hitl.no_pending"] = "No pending checkpoints. Agents are working...",
            ["hitl.expires"]    = "Expires",
            ["hitl.escalate"]   = "↑ Escalate",
            ["hitl.recent"]     = "Recent Decisions",
            ["hitl.title_col"]  = "Title",
            ["hitl.decision"]   = "Decision",
            ["hitl.by"]         = "By",
            ["hitl.at"]         = "At",
            // skills
            ["skills.title"]    = "Skill Registry & Approval",
            ["skills.pending"]  = "Pending Approval",
            ["skills.no_pend"]  = "No skills pending approval.",
            ["skills.def"]      = "Definition",
            ["skills.active"]   = "Active Skills",
            ["skills.filter"]   = "Filter by slug or name...",
            ["skills.slug"]     = "Slug",
            ["skills.scope"]    = "Scope",
            // mcp
            ["mcp.title"]       = "MCP Servers",
            ["mcp.no_data"]     = "No MCP servers found.",
            ["mcp.all"]         = "All",
            ["mcp.endpoint"]    = "Endpoint",
            ["mcp.image"]       = "Image",
            ["mcp.proposed"]    = "Proposed by agent",
            ["mcp.approved_by"] = "Approved by",
            ["mcp.tools"]       = "Tools",
            ["mcp.discover"]    = "🔍 Discover Tools",
            // skills - create
            ["skills.new"]        = "+ New Skill",
            ["skills.new_title"]  = "New Skill",
            ["skills.mandatory"]  = "Mandatory (auto-assigned to agents)",
            ["skills.group"]      = "Group (optional)",
            // agents - templates
            ["agents.tab_agents"]   = "Agents",
            ["agents.tab_tpl"]      = "Templates",
            ["agents.new_tpl"]      = "+ New Template",
            ["agents.new_tpl_title"]= "New Agent Template",
            ["agents.role"]         = "Role",
            ["agents.max_sub"]      = "Max Sub-agents",
            ["agents.skill_groups"] = "Skill Groups (comma separated)",
            ["agents.system_prompt"]= "System Prompt",
            ["agents.no_tpl"]       = "No templates yet. Create one.",
            ["agents.is_global"]    = "Global template",
            ["agents.model"]        = "Model",
            // nav - extras
            ["nav.wiki"]        = "Wiki",
            ["nav.docs"]        = "Documentation",
            ["nav.monitor"]     = "Live Monitor",
            // monitoring sidebar
            ["mon.flows"]       = "active flows",
            ["mon.agents"]      = "active agents",
            ["mon.hitl"]        = "HITL reviews",
            ["mon.skills"]      = "skills pending",
        }
    };
}
